### ISSUE TITLE
Investigate coloured icons for ObO pins

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/owned-by-oxford-project#14]
Can we get them to be coloured by activity like the oxford map (for example)?

**Comment by wu-lee** [comment]
Inspecting the code I discover:
- sea-map uses the Leaflet plugin Awesome Markers
- This has a JS parameter for markers (AKA pins) called `markerColor`
- sea-map passes the primary activity ID there, instead of a colour name
- This works for Oxford because the activity ID is of the form `a10`, `a20` etc. This gets stitched onto a class name, and sea-map has pre-defined appropriate styles defined which match these class names (`awesome-marker-icon-a10` etc.)
- This doesn't work for ObO because it does the same thing, but the activitiy IDs are now in the form `aci:am10` etc. and this doesn't match sea-map's predefined styles

**Comment by wu-lee** [comment]
It is possible to include a map site specific stylesheet with appropriate definitions to make the colours come back.  The main problem is that the way sea-map currently appends IDs onto class names results in an invalid class name (because the ID contains a colon). I can fix this fairly trivially, although perhaps this is best done after finishing the replumbing of sea-map fields I'm currently doing.

**Comment by wu-lee** [comment]
Ok, I've tweaked sea-map to sanitise the vocab IDs before embedding them in a CSS class, so now along with a site-specific stylesheet, the coloured markers are back.  Enabling an option brings back colour to the directory.

I've also rediscovered why the vocab query is slow: no default graph URI supplied in the config.  This was removed earlier because the config is shared by all vocabs, which makes for a problem when there are multiple datasets.  One of those things we need to fix before multi-dataset maps will work fully.

Map deployed and visible here: https://ownedbyoxford.org.uk/our-map/

**Comment by ColmMassey** [comment]
I am seeing 2 colours sometimes when I expect just 1. 

![2-colours](https://user-images.githubusercontent.com/1162642/159978003-92247214-be5a-4f5c-b043-bc666fb33218.png)

**Comment by wu-lee** [comment]
Can't seem to replicate this? All three food markers are green for me, and checking all other single-category selections gets just one colour of marker

**Comment by ColmMassey** [comment]
I can now no longer replicate it. Must have been some intermediate state...
