### ISSUE TITLE
Put OBO map in their Wordpress site

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/owned-by-oxford-project#15]
Creating a ticket here, as this ended up being trickier than expected. Can we copy in any notes/email exchanges that capture what the issue was, for future reference. What did we need to do in the end to fix the issue. Add the link to the wordpress page where the map is now displayed.

**Comment by wu-lee** [comment]
The steps needed for a Wordpress.com site is:
- Upgrade to Business Plan. (This is the lowest level which supports the custom elements needed.)
- Create a Custom HTML block in the desired place. (An embed block is limited to a selection of whitelisted sites like You Tube, and will refuse to embed the SEA maps, even with Business Plan.)
- Insert the appropriate iframe tag. For example: `<iframe id="sea-map-iframe"
src="https://maps.solidarityeconomy.coop/obo-public/?showDatasetsPanel=false&disableClusteringAtZoom=12&maxZoomOnOne=8" style="width:100%; height: 500px;"></iframe>`
- Optionally, add a button block next to the map saying "Open Map in Full Screen" which opens the map link in a new window, for example: `https://maps.solidarityeconomy.coop/obo-public/`

If the site is not on Wordpress.com, there may be a different prerequisite plan required. If it is on a self-hosted Wordpress installation, custom elements should be allowed by default.

**Comment by ColmMassey** [comment]
And where is it displayed?

**Comment by wu-lee** [comment]
The Owned by Oxford map is here: https://ownedbyoxford.org.uk/our-map/

**Comment by ColmMassey** [comment]
I think we need to help them choose better URL arguments. 

It should zoom to oxforshire and have the markers unclustrered I reckon. I wonder about the dialog/frame ratio. I think I'll bring @MelissaMc20 in here..Mel, are you familiar with the currently avaialble url arguments folks can set to configure their maps? 

What was the last conversation I saw re marker colours. It wasn't the wordpress set up that was blocking them working?

**Comment by ColmMassey** [comment]
https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/CONFIG.md

I think they may need different parameters depending on if it is in that narrow iframe or in the full screen.

**Comment by wu-lee** [comment]
I don't expect Mel will know about the parameters for sea-map.

The ones currently could be improved, agreed. sea-map is supposed to auto-zoom I think but the config has inherited an `initialBounds` setting which prevents that. I've removed that just now, so it zooms in.  Possibly too much?  But this discussion doesn't belong in this ticket.

Generally the above assumes the site is configured correctly. There is no hard-and-fast rule about what parameters to set, either in the config or the iframe embed URL. I just reused and lightly edited the parameters which the Mersey Green Map was using.

**Comment by wu-lee** [comment]
> What was the last conversation I saw re marker colours. It wasn't the wordpress set up that was blocking them working?

No, it was that the newer version of sea-map's hardwired pin styles don't work with its way of representing vocab IDs. 

See #14

**Comment by ColmMassey** [comment]
@MelissaMc20, the marker colours are working as expected now, and the default zoom seems fine, so I think the only remaining tweak we could do atm is the dialog sizes. I think we need more than one set of dialog size configs. 

At least we need one set for the full screen and one for in the wordpress page.

We also have the problem of narrow/phone screens when on the wordpress page. That might not be possible to tweak with just url parameters, so let's leave that for now. @MelissaMc20, do you have time today or early next week to get your head around how the url paramters work for dialog ratios and recommend some settings for the full screen and also for when still in the wordpress iframe? I am happy to walk you through them.

**Comment by MelissaMc20** [comment]
@ColmMassey I have time this afternoon if that works for you?

**Comment by ColmMassey** [comment]
> 

3:00?

**Comment by MelissaMc20** [comment]
Works for me

**Comment by King-Mob** [comment]
Screenshots of the different options on the wordpress. I generated them by changing the iframe link using the dev tools. The first one was changed from `https://maps.solidarityeconomy.coop/obo-public/?showDatasetsPanel=false&disableClusteringAtZoom=12&maxZoomOnOne=8` to `https://maps.solidarityeconomy.coop/obo-public/?showDatasetsPanel=false&disableClusteringAtZoom=12&maxZoomOnOne=8&dialogueSize=width:40vw,height:200px,descriptionRatio:2` 

Then I just changed the value of the width.

40vw:
![obo dialogue 40vw](https://user-images.githubusercontent.com/38507954/160848895-018b5188-63cf-4762-a4ac-49a627cea3d2.png)
50vw:
![obo dialogue 50vw](https://user-images.githubusercontent.com/38507954/160849127-2cfbd598-d253-42f0-824a-d2c1e62cfb7d.png)
60vw:
![obo dialogue 60vw](https://user-images.githubusercontent.com/38507954/160849160-f705f40c-d355-4d7a-8127-6c5aa7372410.png)

**Comment by ColmMassey** [comment]
>Big fan of the 60vw but at a push 40vw works

Happy for you to make that call and we can see what the client says. Also need to see how it behaves/looks with panels open.

**Comment by ColmMassey** [comment]
So we need proposed URL arguments for when the map is within wordpress page and also standalone?

**Comment by wu-lee** [comment]
This is what @King-Mob proposed we use for ObyO.

https://maps.solidarityeconomy.coop/obo-public/?showDatasetsPanel=true&disableClusteringAtZoom=12&maxZoomOnOne=8&dialogueSize=width:60vw,height:200px,descriptionRatio:2

I've updated their Wordpress page here:

https://ownedbyoxford.org.uk/our-map/

But equally we could put those configs into the deployment.

**Comment by ColmMassey** [comment]
Slightly concerned there may be too many cooks on this one. ;-) @MelissaMc20 are you happy that these settings look good on all screen options, whith panels opened and closed?

**Comment by MelissaMc20** [comment]
Slightly concerned that the box is increasing past the 'normal' width when on view full map. Is it possible to set a max width depending on screen size? @King-Mob 

Also If panels are open, it should react as if the screen was decresing in width - as technically that is what's happening.
