### ISSUE TITLE
Linking to data from other sources through Airtable

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/owned-by-oxford-project#17]
We need to design a workflow where data from sources like Co-ops uk is visible in the Airtable interface where OBO team members can select them, add extra parameters not specified from that source, like Primary Activity, Relationship to OBO, etc but without creating a duplication of data that will cause problems in the future. 

Using this ticket to propose a workflow to evaluate.

- Create a csv table of oxford co-ops from the co-ops uk data set 
- Import the table into Airtable
- Create a new column in the Organisations ObO table called External Initiative, which allow users to select a coop from the new Co-ops Uk table as an entry.
- Create a new, read only column in the Organisations ObO table called External Initiative Ref, whose entires are autopopulated with the uri of the initiative selected in the External Initiative Ref.
- Test the above workflow by creating some Newcos using this method of referencing a co-op from the other table.
- Does it break the sausage factory straight away?
- Check that all the data we expect to be getting through to the maps still are.
- Once this all works we 
  - can look at how to use the data from the non airtable sources, for addresses etc, either by auto populaitng more columns in the Organisations Obo table, or by doing some sort of post Airtable merge. 
  - look at adding other data sources, like good food oxford to the External Initiative table.
  - think through how fragile this is if we need to update the External Initiative table.

**Comment by ColmMassey** [comment]
@wu-lee "After rather more fidding than I'd  anticipated (our standard.csv files have different fields in some datasets, etc.) I've imported a table to Airtable which has the Oxford-postcoded entries
There  may be some rough edges. e.g Twitter and Facebook URIs have their stems truncated as in the data. 
Presumably the simple filtering on Postcode will have filtered out Co-ops UK entries for organisations which may have outlets in Oxford but whose HQ is not - not sure what to do about that.
I've added a URI field by concatenating the Identifier field to the end of a base URI for each dataset"

**Comment by ColmMassey** [comment]
So that is the first two steps but for all the external datasets. Next step is to create the new columns and see how we can pull data from there into Organisations Obo.

**Comment by wu-lee** [comment]
I've added the columns.  It works as expected, nominally.  The main annoyance is that Airtable's search dialog for adding the link is obtuse.  It shows the "primary field" first and foremost, which is the URI (that's the only guaranteed unique field.)  I don't really want that to get emphasised - I want the name, address, description and postcode to be.  This does not appear to be an option: although I can select the "view" it uses for the dialog, creating several views and trying each in turn seems to get... exactly the same dialog with the same problems.

The worst thing is that searching only searches the primary field - so I cannot search for (for example) "Solidarity" and find the Solidarity Economy Association. I have to know the ID, as this is the only field the search seems to match against.  This is very limiting.

**Comment by wu-lee** [comment]
With respect to the sausage machine: it will not break because a new field is added. The downloaded JSON file is converted to CSV, and only selected fields are used for the conversion, any others are ignored. Removing or renaming fields might break it, but we are not doing that.

**Comment by ColmMassey** [comment]
> With respect to the sausage machine

Sorry for dising the Sausage Machine.

**Comment by wu-lee** [comment]
Fragility, problems:
- On linking, seems there's an option to add records, which could be abused.
- The search is rubbish. [Can't see a way to make it less rubbish.](https://community.airtable.com/t/search-in-all-fields-link-to-record/32906/2)
- There may be several valid matches for an organisation
  - Which one to use?
  - Should we allow many links?
  - How does one know to keep looking?
  - Given many are linked external initiatives, they have equal (or practically indistinguishable) precedence, so should we want to acquire fields such as "address" from them, which one?

**Comment by ColmMassey** [comment]
> It shows the "primary field" first and foremost,

If you have 2 browser tabs open, one with the _External Initiative_ table open and the other open at _Organisations ObO_ you can do the search in one, copy the uri from the one you like and swap tabs and then use that to search when you attempt to add a new entry in the _External Initiative_ column.

Not slick, but only a few seconds per link made.

**Comment by ColmMassey** [comment]
Given that the _External Initiative_ column in the _Organisations ObO_ table must display the URI, can we change the _External Initiative Ref_ to be _External Initiative Name_ as 'visual clue' that a valid link has been made.

**Comment by ColmMassey** [comment]
"Which one to use?
  Should we allow many links?
  Given many are linked external initiatives, they have equal (or practically indistinguishable) precedence, so should we want to acquire fields such as "address" from them, which one?"

Let start by only allowing one link. The admin will need to make an informed choice as to the most useful one. And give priority to entries manually entered in Airtable. If the admin trusts the other source, they should delete their manual entry.

When converting the JSON to CSV can you easily get the relevant field values from the uri provide?

**Comment by wu-lee** [comment]
No respect to Airtable, I adjusted the export to put the `Name` field first, so now it isn't unique (Airtable uses an internal ID for that I think), but the linked-record search is at least marginally usable.

Then I read your comments - so see what you think? I can switch back if necessary.

[Edit] The problem with simply linking to the name in a second field is that you only see that *after* linking it. So you still need faff about switching tables to check what magic text to search for in the dialog.  Now at least you can do the obvious thing, and the field shows then name by default.  (The exported value is the internal Airtable ID in any case, however, so we will need to add linked fields for the URI and any other External Initiatives field we want to capture)

**Comment by wu-lee** [comment]
Oops, wrong button. 

Yes - there is only one link to another record allowed at the moment.

> When converting the JSON to CSV can you easily get the relevant field values from the uri provide?

Not sure what you mean there?

If you mean index them from other datasets after exporting - no. If you mean can we add them as linked fields before exporting - yes.

**Comment by ColmMassey** [comment]
> No respect to Airtable, I adjusted the export to put the `Name` field first, so now it isn't unique (Airtable uses an internal ID for that I think), but the linked-record search is at least marginally usable.

That is a lot more usable. When there are multiple identical names, like Woodcraft Folk, they need to be careful to select the right one, by looking at postcodes etc. But usable, I think.

**Comment by ColmMassey** [comment]
> Not sure what you mean there?
> 
> If you mean index them from other datasets after exporting - no. If you mean can we add them as linked fields before exporting - yes.

I think we need a chat to explore this. What's your timtable like today?

**Comment by wu-lee** [comment]
Maybe at the end of the 1.30 DC/CO meeting?

**Comment by ColmMassey** [comment]
So we can restructure the imported csv file that populates the External Initiatives table to that it includes a column indicating the data source. We can then create a custom view, so that when searching for the correct _External Initiative_ in the list, the user can see Name, Description, Data Source and Postcode. Should cover 99% of searches. We then create columns of derived fields, called  _External Name_, _External Postcode_ etc, which are pulled from the linked table entry, if there is a blank entry in its respective manually entered field. If there is something in the manually entered field, that is used instead. This means that the 'merge' is done in Airtable, simplifying changes required to sausage factory.

**Comment by ColmMassey** [comment]
If we are doing it this way, it the name _External Postcode_ etc. aren't quite right. Something like _Selected Postcode_ or something like that?...

**Comment by ColmMassey** [comment]
This now works. @wu-lee do you want to add any more comments here, for the record and then we can close the issue?

**Comment by wu-lee** [comment]
The only thing I might add is that there is still a manual step to update the table in Airtable, suing a Ruby script which non-destructively replaces the data there with data collected from the standard.csv files in a local install of open-data. But this seems fine.
