### ISSUE TITLE
Missing co-op

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/owned-by-oxford-project#2]
The Renewable Energy coop is on the dotcoop map as it has the domain http://r-eco.coop
It is also on the https://coopsuk.solidarityeconomy.coop/ website.

It's postcode is OX2 6HQ, however it doesn't appear in the directory on the owned by oxford website. If you search for it with key word search, it is in there twice as expected. So the directory is missing it for some reason.

**Comment by wu-lee** [comment]
Is this resolved now the directory is implemented? I see the missing initiative in the directory.

(Actually, also now that I fixed a bug in the postcode-shortener, which used to smoosh postcodes like `OX2 6TP` into `OX26TP` and then extract the short postcode as `OX26`. It doesn't smoosh now, so this case gets `OX2` as expected; pre-smooshed postcodes from the data still will, however, and I'm not sure how to solve that in a simple way using regular expressions...)

**Comment by ColmMassey** [comment]
Great.
