### ISSUE TITLE
Update and tidy the Owned-by-Oxford map

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/owned-by-oxford-project#26]
The development and production deployments could benefit from an update. (Especially the latter, last deployed in Dec 22)

The production and development map links, respectively, for reference:
- https://maps.solidarityeconomy.coop/obo-public/ (updated manually)
- https://dev.maps.solidarityeconomy.coop/obo-public/ (updated on pushes to the `dev` branch)

Aside - there is also this testing version, which should not be confused with the above two:
- https://dev.maps.solidarityeconomy.coop/temp/obo-public/ (updated with the `dev` branch of the map on pushes to the mykomap `testing` branch - used for testing bleeding-edge versions of mykomap)

There is a OBO development map update report [here][1]
and Next Dev Tasks for OBO Map [here](https://docs.google.com/document/d/1qc5-tIHb8-CnCY4DqabyCcja-9w_1M6HkhCn9ijJxU4/edit?usp=sharing)

Update the development version as follows:
- [x] use the latest version of mykomap
- [x] utilise ability to use friendly search filter titles
- [x] clean up the pop-up to match content described in the report linked above
- [x] add new text to about box
- [ ] make about box the default panel and the open on startup
- [ ] ~~add post code and organistion type filters~~ 

[1]: https://docs.google.com/document/d/1A_SS-2DfedgF2jNuHwt8YdWsaUkuFrF3ZgXzrhWYngQ/edit?skip_itp2_check=true

**Comment by wu-lee** [comment]
Note, the production version has been replaced with a cut-and-paste copy of the development version, in advance of the review meeting of 16/11/23

**Comment by wu-lee** [comment]
This is an attempt to make itemise in more detail the things proposed in the documents above (OBO development map update report and Next Dev Tasks for OBO Map)
- update to the latest version of mykomap (MM 3.1.4) - *done*
- add post code and organisation type filters
    - add a "nature of organisation" vocab (custom, defined in `obo.json` file included with map) with these terms in English: *done*
      - `communityEnt`: "Community Enterprise"
      - `supportOrg`: "Support Organisation"
    - set `natureOfOrganisation` field as filterable and searchable - *done*
    - add (short) postcode as a filterable field - *can't yet be done, see comment below*
- utilise ability to use friendly search filter titles
    - reorder and (where needed) retitle filterable fields as: *done, excepting postcode*
      - Organisation type (`natureOfOrganisation`)
      - Primary activity (`primaryActivity`)
      - All activities (`combinedActivities`)
      - Governance structure (`orgStructure`)
      - Postcode (`shortPostcode`)
- clean up the pop-up to match content described in the report "OBO development map update report" *best effort done, needs review*
   - See example pop-up text with approximate ordering/layout below
- add new text to about box *done, also needs review*
   - ...Or as best will fit in the constraints
   - See cleaned up "about" text below 
- make about box the default panel and the open on startup
  - open sidebar by default - *done but oddly **not** inhibited by MM bug https://github.com/DigitalCommons/mykomap/issues/226*
  - show about panel by default - *this is not currently possible in MM*

Later:
- Add CPV as category. (Requires modifying Airtable, the data feed converter, and the map) See https://github.com/DigitalCommons/owned-by-oxford-project/issues/29

---
Pop-up layout. 

Left panel example:
> ## Arts Community Enterprise Co-op
> Community Enterprise
> 
> Community Benefit Society (CBS)
> 
> Sectors and activities include: 
> - Arts, Media, Culture & Leisure
> - Health, Social Care & Wellbeing
> 
> ACE Co-op runs art and creative activities for children and young people on the Ace Estate.
> 

Right panel example:

> ## Contact:
> ACE Co-op
> Address: ...
> Tel number: ...
> Email: ...
> [Social media icons]
> 

---

About text: 

>     <h2>About this map</h2>
>     <p>The organisations on our map are all working in their local areas to build a more inclusive and sustainable economy.</p>
>     <p>The solution to many of the economic and social issues in our lives can be addressed by putting more power and wealth in the hands of the people who best understand the strengths and needs of their own communities.</p>
>     <p>This map is all about making these enterprising, community-led responses more visible. And increasing the collaboration and connections between them.</p>
>     <p>If you work in an organisation that buys goods or services and want to make a difference in reducing inequality and empowering local people, this map provides a directory to help you find what you’re looking for from an organisation with guaranteed social and community purpose.</p>
>     <p>If you are involved in or want to set up a community enterprise, then this map will help you to:</p>
>     <ul>
>       <li>sell your goods and services.</li>
>       <li>find partners to collaborate with.</li>
>       <li>find organisations offering development support and training.</li>
>     </ul>
>     <p>We will be adding new organisations over time, so keep coming back if you can’t find what you’re looking for. And if you know an organisation that fits this profile that should be added let us know by getting in touch here.</p>
>     <h3>How to use the map</h3>
>     <p>If you click on “Directory” above you will find a list of categories to select from. Select a category and the map will show you all the organisations working in this field.Then click on the “pin” on the map to get more information about each organisation.</p>
>     <p>The info box for each pin will tell you whether the organisation is a “Community Enterprise” or a “Support Organisation”.</p>
>     <p>Community Enterprises have been assessed by ObO as meeting or working towards the following criteria:</p>
>     <ul>
>       <li>Not for profit</p></li>
>       <li>Locally owned and community-led</p></li>
>       <li>Providing local community benefit</p></li>
>       <li>Regenerative</p></li>
>     </ul>
>     <p>Support organisations provide training, business and development support accessible to community enterprise</p>
>     <p>This<a      href="https://www.digitalcommons.coop/mykomaps/">Mykomap</a> has been created by the<a href="https://www.digitalcommons.coop/">Digital Commons Co-operative</a> for the <a href="https://ownedbyoxford.org.uk/">>Owned By Oxford</a>project.</p>
>     <p>mykomap@3.1.4</p>
>     <p>You can also use the “Search” function which gives you the options to choose from different filters or use a word search.</p>

**Comment by wu-lee** [comment]
Note - the data factory's attempt to download the ObO data from Airtable is erroring with a 403 (unauthorised) - will need to look into that.

**Comment by wu-lee** [comment]
Can't add short postcode as a dropdown yet - needs https://github.com/DigitalCommons/mykomap/issues/201 to have been implemented (as it's not a vocab and can't easily be made into one like `natureOfOrganisation`).

**Comment by wu-lee** [comment]
There's a map published now, here: https://dev.maps.solidarityeconomy.coop/obo-public/

Some outstanding points:
- I've amended the about text to refer to the icons descriptively, rather than by name (which is not visible)
- The "getting in touch" link is still missing
- Now the Nature of Organisation taxonomy is used on the directory panel, the hardwired colours for "Activities" are gone. Can't be fixed without unhardwiring, a feature related to this Epic https://github.com/DigitalCommons/owned-by-oxford-project#workspaces/megaboard-639bb01fc526ef0010ab662b/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzMTE2

**Comment by wu-lee** [comment]
Airtable's API authentication requirements have changed and have broken / will break the feed, see https://github.com/DigitalCommons/open-data/issues/185

**Comment by ColmDC** [comment]
Awaiting review by someone from OBO.

**Comment by ColmDC** [comment]
Dropping the postcode specific feature as an OBO feature to be completed under OXON Connect.

**Comment by ColmDC** [comment]
Closing this Issue as it is straggling. Outstanding Issues for OBO Map can be found this project.

https://github.com/orgs/DigitalCommons/projects/8/views/2
