### ISSUE TITLE
ObO map doesn't update directory tab when dataset changed

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/owned-by-oxford-project#6]
the directory tab seems to contain a full list of initiatives whatever data set is selected

also, there seems to be a bug in the  directory - after some use of filters / datasets, clicking the items no longer zooms to the pin - but there is an error in the console,

**Comment by wu-lee** [comment]
@ColmMassey - what should we show in the directory tab?

Vocabs (org. structure, activities) don't seem to be appropriate, most initiatives don't have these (only Solidarity Oxford). Region might be - if they can be made consistent across datasets to mean an Oxfordshire region.  Is there anything else more suitable?

**Comment by wu-lee** [comment]
Also: can't currently replicate this bug, and for now I've removed all filterable fields, because the 1.x sea-map code doesn't currently support filterable fields which are not vocab terms.  So nothing shows in the directory, and there are no drop-downs.

**Comment by ColmMassey** [comment]
> 
> 
> @ColmMassey - what should we show in the directory tab?
> 
> Vocabs (org. structure, activities) don't seem to be appropriate, most initiatives don't have these (only Solidarity Oxford). Region might be - if they can be made consistent across datasets to mean an Oxfordshire region. Is there anything else more suitable?

For now I think it needs to be geographic. Can we filter by the first half of the postcode?

**Comment by wu-lee** [comment]
See #3, now deployed

**Comment by ColmMassey** [comment]
The directory not updating bug is still there. But actually it is limited to the Covid-Mutual-Aid data...

**Comment by wu-lee** [comment]
I think this is that, although we limit the covid-mutual-aid data to those items with Oxford postcodes in the `street` attribute, we don't currently have a way to get that postcode into the `postcode` (and thereby the `shortPostcode` attribute using SPARQL.  So these initiatives have no entries in the directory.

I'll see if I can find a SPARQL1.0 (Virtuoso) friendly way to do that - in general it seems to need the 1.1 BIND feature.  If not, I may need to alter the covid-mutual-aid data conversion to do it.

**Comment by wu-lee** [comment]
>  If not, I may need to alter the covid-mutual-aid data conversion to do it.

Correction: actually, I already did that - just the postcode isn't included in the query. I've added it to ObO's query for CMA now, and that seems to have done the trick.

Doing it in SPARQL1.0 doesn't seem easy, so far there seems to be a way to add a constant field, not sure if this can be extended to one computed from the others...
