### ISSUE TITLE
Create Public Map for OBO Website

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/owned-by-oxford-project#8]
Create a 'clean' sea-map which will be used for the public face of the OBO project. 

- [x] - Create it at obo-public for now.
- [x] - Only include the airtable dataset to start.
- [x] - Choose style of map tiles used. See https://www.thunderforest.com/ for options.
- [x] - Put sensible text in the about/info box.
- [ ] - Check it works fine in the wordpress iframe.
- [ ] 

See https://github.com/SolidarityEconomyAssociation/owned-by-oxford-project/issues/1 for original ticket.

**Comment by ColmMassey** [comment]
@MelissaMc20 can you add any features we may have discussed that would be specific to the public OBO map here?

**Comment by ColmMassey** [comment]
https://jamboard.google.com/d/1Ukiym4nlhFiyMKtyNz2iSusUZzx77stDRjcMdGnH8Ds/viewer?f=5

**Comment by MelissaMc20** [comment]
[[- Layers to be able to switch round, something that would let you put one layer on top of the other when toggled on, and to be able to switch them round if sections from one layer are appearing under another (therefore not selectable) 
- Clicking the polygons on the toggle layers to give information as to why they're categorised the way they are ]]

- Colour co-ordinated marker pins for each section (mixed to show up one colour with a key on the info section to discuss how many there were) 
- Wanna be able to highlight to differentiate between data they want to highlight against background data. What are the options for different types of highlighting? If it's in oxford table, it's brighter.. from different sources?

I've sectioned off the top features as I'm not sure if they were specific to the public facing OBO (we were looking at the LX site at the time and discussed so many things in on section it's a little bit blurry where they don't overlap)

**Comment by wu-lee** [comment]
https://dev.maps.solidarityeconomy.coop/obo-public/

These are done, but leaving checkbox checking for you after validation:
- Create it at obo-public
- Only include the airtable dataset (called `owned-by-oxford`)
- Put sensible text in the about/info box.

The code is still in the owned-by-oxford project, I've just split the `dev` branch into `public/dev` and `private/dev` branches. The idea being that it's easier to port across changes from one to the other branch if they're in the same project. We'll see how that goes.

I didn't do these yet:
- Choose style of map tiles used: I could pick one, but my choice would be arbitrary. Presumably ObO themselves need to pick one?
- Check it works fine in the wordpress iframe: I'm pretty sure it will, but more to the point, I can't remember where to find the ObO WordPress site?

Also: what kind of things do I need to get from @MelissaMc20 - do they require sea-map modifications?

**Comment by ColmMassey** [comment]
> I didn't do these yet:

I've emailed the CAG comms person who is doing the website. We are not hosting it. Did you see that email. I'll respond to the UI issues in another thread.

**Comment by ColmMassey** [comment]
> * Clicking the polygons on the toggle layers to give information as to why they're categorised the way they are ]]

This is a LE feature as no current plans to add polys to sea-map.
